version: "2"

services:
  php-wallet:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./docker/php7-fpm
    image: laravel:php-fpm
    container_name: php-wallet
    entrypoint:
      - php-fpm
    environment:
      DEBUG: 'true'
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
  web-wallet:
    image: nginx:alpine
    container_name: nginx-wallet
    depends_on:
      - php-wallet
    volumes_from:
      - php-wallet
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 81:81
  db-wallet:
    image: mysql
    container_name: db-wallet
    command:
      - --default-authentication-plugin=mysql_native_password
      - --sort_buffer_size=1073741824
    restart: always
    volumes:
      - "./db:/var/lib/mysql"
      - "./docker/init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
